sailscastshq/boring-stack

create-sails/actions/download-project.js
create-sails/actions/frontend.js
create-sails/index.js
create-sails/package-lock.json
create-sails/package.json

[feat] implement downloading project from templates

---

create-sails/index.js

[fix] Update sails lift command

---

README.md

Chore: Fix duplicate typo error on README

---

templates/mellow-react/README.md
templates/mellow-react/package.json
templates/mellow-svelte/README.md
templates/mellow-svelte/package.json
templates/mellow-vue/package.json

[chore] Update package name and fix a minor typo in the README file

---

inertia-sails/index.js
inertia-sails/private/inertia-middleware.js
inertia-sails/private/resolve-validation-errors.js

[feat] add support for validation errors

---

inertia-sails/private/resolve-validation-errors.js

[fix] return errors as string if only one exists

---

CONTRIBUTING.md

[chore] Add List of Commit types and their Description, with examples

---

CONTRIBUTING.md

This PR fixes the typo in contribtuing.md file.
Closes #46

Fixed the typo in CONTRIBUTING.md

---

CONTRIBUTING.md

[chore]: Add link to first-time contributor guide in contributing.md

---

templates/mellow-vue/tests/e2e/signup.spec.js

chore(mellow-vue): refactor test to use recommended locators

---

templates/mellow-vue/jsconfig.json

fix(mellow-vue): add paths and baseUrl to compilerOptions

---

templates/mellow-svelte/assets/js/pages/index.svelte

Link was pointing to an akward page

Corrected the link to webpack

---

inertia-sails/package.json
inertia-sails/private/inertia-middleware.js
inertia-sails/private/resolve-validation-errors.js

[feat] implement handling validation errors and flash messages

---

inertia-sails/index.js
inertia-sails/private/inertia-middleware.js

[feat]: use responses and exits

---

templates/mellow-react/api/controllers/example/index.js
templates/mellow-react/api/controllers/home/index.js
templates/mellow-react/api/responses/badRequest.js
templates/mellow-react/api/responses/expired.js
templates/mellow-react/api/responses/inertia.js
templates/mellow-react/api/responses/inertiaRedirect.js
templates/mellow-react/package-lock.json
templates/mellow-react/package.json
templates/mellow-svelte/api/controllers/example/index.js
templates/mellow-svelte/api/controllers/home/index.js
templates/mellow-svelte/api/responses/badRequest.js
templates/mellow-svelte/api/responses/expired.js
templates/mellow-svelte/api/responses/inertia.js
templates/mellow-svelte/api/responses/inertiaRedirect.js
templates/mellow-svelte/package-lock.json
templates/mellow-svelte/package.json

[feat]update mellow svelte to latest syntax

---

templates/mellow-react/config/blueprints.js
templates/mellow-svelte/config/blueprints.js
templates/mellow-vue/config/blueprints.js

This PR solves issue: #96 
Do review and provide feedback if any @DominusKelvin

chore: turn off blueprints on all templates

---

create-sails-generator/generators/page/index.js
create-sails-generator/package.json
templates/mellow-react/assets/dependencies/sockets.js
templates/mellow-react/package-lock.json
templates/mellow-react/package.json
templates/mellow-react/views/app.ejs
templates/mellow-svelte/assets/dependencies/sockets.js
templates/mellow-svelte/package-lock.json
templates/mellow-svelte/package.json
templates/mellow-svelte/views/app.ejs
templates/mellow-vue/assets/dependencies/sockets.js
templates/mellow-vue/package-lock.json
templates/mellow-vue/package.json
templates/mellow-vue/views/app.ejs

[feat] update starter templates to shipwright v0.2.0

---

packages/inertia-sails/lib/location.js

fix(inertia-sails): resolve regression in inertiaRedirect

---

templates/mellow-react/api/controllers/auth/resend-link.js
templates/mellow-react/api/controllers/auth/view-success.js
templates/mellow-svelte/api/controllers/auth/resend-link.js
templates/mellow-svelte/api/controllers/auth/view-success.js
templates/mellow-vue/api/controllers/auth/resend-link.js
templates/mellow-vue/api/controllers/auth/view-success.js

Closes https://github.com/sailscastshq/boring-stack/issues/130

fix: resend-link.js syntax error and resend link messaging

---

templates/mellow-react/package-lock.json
templates/mellow-svelte/package-lock.json
templates/mellow-vue/package-lock.json

fix: regenerate package-lock.json to resolve Node 23 incompatibility
